apiVersion: v1
kind: Secret
metadata:
  name: adoptme-secrets
type: Opaque
stringData:
  mongo-url: "mongodb+srv://admin:Vamoaggro.1991@cluster0.4cbay0m.mongodb.net/adoptme"
  jwt-secret: "tokenSecretJWT"